


RANGE_X = 80
RANGE_Y = 80

CLASS_NUM = 3

MAX_PILLAR_NUM = 1600

PILLAR_SIZE_X,PILLAR_SIZE_Y = 1/3., 1/3. #meter

IMAGE_DIMENSION = [int(RANGE_X/PILLAR_SIZE_X), int(RANGE_Y/PILLAR_SIZE_Y)]

IAMGE_COORD_OFFSET = [IMAGE_DIMENSION[0], IMAGE_DIMENSION[1]]

MIN_POINTS = 40
POINT_FEATURE_LENGTH = 9
PILLAR_IMAGE_HEIGHT = int(RANGE_X/PILLAR_SIZE_X)
PILLAR_IMAGE_WIDTH  = int(RANGE_Y/PILLAR_SIZE_Y)
#H,W,P,D = [int(RANGE_X/PILLAR_SIZE_X), int(RANGE_Y/PILLAR_SIZE_Y), MIN_POINTS, POINT_FEATURE_LENGTH]

OBJECT_OFFSET_RADIUS = int(2/PILLAR_SIZE_X)

MIN_POINTS_PER_PILLAR = 10
